<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:activities="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//activities" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="EmoflonExampleCode" nsURI="platform:/plugin/EmoflonExampleCode/model/EmoflonExampleCode.ecore" nsPrefix="EmoflonExampleCode">
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eOperations xsi:type="activities:MoflonEOperation" name="count">
      <activity owningOperation="//Container/count">
        <ownedActivityEdge source="//Container/count/@activity/@ownedActivityNode.0" target="//Container/count/@activity/@ownedActivityNode.1"/>
        <ownedActivityEdge source="//Container/count/@activity/@ownedActivityNode.1" target="//Container/count/@activity/@ownedActivityNode.2"/>
        <ownedActivityEdge source="//Container/count/@activity/@ownedActivityNode.2" target="//Container/count/@activity/@ownedActivityNode.3" guard="SUCCESS"/>
        <ownedActivityEdge source="//Container/count/@activity/@ownedActivityNode.2" target="//Container/count/@activity/@ownedActivityNode.4" guard="FAILURE"/>
        <ownedActivityEdge source="//Container/count/@activity/@ownedActivityNode.3" target="//Container/count/@activity/@ownedActivityNode.4" guard="SUCCESS"/>
        <ownedActivityEdge source="//Container/count/@activity/@ownedActivityNode.3" target="//Container/count/@activity/@ownedActivityNode.4" guard="FAILURE"/>
        <ownedActivityNode xsi:type="activities:StartNode" outgoing="//Container/count/@activity/@ownedActivityEdge.0"/>
        <ownedActivityNode xsi:type="activities:StoryNode" name="one" comment="one" outgoing="//Container/count/@activity/@ownedActivityEdge.1" incoming="//Container/count/@activity/@ownedActivityEdge.0">
          <storyPattern comment="one">
            <objectVariable type="//Container" name="this" outgoingLink="//Container/count/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0 //Container/count/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.1" bindingState="BOUND"/>
            <objectVariable type="//Marker" name="marker1" incomingLink="//Container/count/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.1"/>
            <objectVariable type="//One" name="one" incomingLink="//Container/count/@activity/@ownedActivityNode.1/@storyPattern/@linkVariable.0" bindingOperator="CREATE"/>
            <linkVariable name="counters" target="//Container/count/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.2" source="//Container/count/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0" type="//Container/counters" bindingOperator="CREATE"/>
            <linkVariable name="markers" target="//Container/count/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.1" source="//Container/count/@activity/@ownedActivityNode.1/@storyPattern/@objectVariable.0" type="//Container/markers"/>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StoryNode" name="two" comment="two" outgoing="//Container/count/@activity/@ownedActivityEdge.2 //Container/count/@activity/@ownedActivityEdge.3" incoming="//Container/count/@activity/@ownedActivityEdge.1">
          <storyPattern comment="two">
            <objectVariable type="//Container" name="this" outgoingLink="//Container/count/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.0 //Container/count/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.1 //Container/count/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.2 //Container/count/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.3" bindingState="BOUND"/>
            <objectVariable type="//Marker" name="marker1" incomingLink="//Container/count/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.0" bindingState="BOUND"/>
            <objectVariable type="//Marker" name="marker2" incomingLink="//Container/count/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.2"/>
            <objectVariable type="//Two" name="two" incomingLink="//Container/count/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.1" bindingOperator="CREATE"/>
            <objectVariable type="//One" name="one" incomingLink="//Container/count/@activity/@ownedActivityNode.2/@storyPattern/@linkVariable.3" bindingOperator="DESTROY" bindingState="BOUND"/>
            <linkVariable name="markers" target="//Container/count/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.1" source="//Container/count/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.0" type="//Container/markers"/>
            <linkVariable name="counters" target="//Container/count/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.3" source="//Container/count/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.0" type="//Container/counters" bindingOperator="CREATE"/>
            <linkVariable name="markers" target="//Container/count/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.2" source="//Container/count/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.0" type="//Container/markers"/>
            <linkVariable name="counters" target="//Container/count/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.4" source="//Container/count/@activity/@ownedActivityNode.2/@storyPattern/@objectVariable.0" type="//Container/counters" bindingOperator="DESTROY"/>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StoryNode" name="three" comment="three" outgoing="//Container/count/@activity/@ownedActivityEdge.4 //Container/count/@activity/@ownedActivityEdge.5" incoming="//Container/count/@activity/@ownedActivityEdge.2">
          <storyPattern comment="three">
            <objectVariable type="//Container" name="this" outgoingLink="//Container/count/@activity/@ownedActivityNode.3/@storyPattern/@linkVariable.0 //Container/count/@activity/@ownedActivityNode.3/@storyPattern/@linkVariable.1 //Container/count/@activity/@ownedActivityNode.3/@storyPattern/@linkVariable.2 //Container/count/@activity/@ownedActivityNode.3/@storyPattern/@linkVariable.3 //Container/count/@activity/@ownedActivityNode.3/@storyPattern/@linkVariable.4" bindingState="BOUND"/>
            <objectVariable type="//Marker" name="marker1" incomingLink="//Container/count/@activity/@ownedActivityNode.3/@storyPattern/@linkVariable.0" bindingState="BOUND"/>
            <objectVariable type="//Marker" name="marker2" incomingLink="//Container/count/@activity/@ownedActivityNode.3/@storyPattern/@linkVariable.1" bindingState="BOUND"/>
            <objectVariable type="//Marker" name="marker3" incomingLink="//Container/count/@activity/@ownedActivityNode.3/@storyPattern/@linkVariable.2"/>
            <objectVariable type="//Three" name="three" incomingLink="//Container/count/@activity/@ownedActivityNode.3/@storyPattern/@linkVariable.3" bindingOperator="CREATE"/>
            <objectVariable type="//Two" name="two" incomingLink="//Container/count/@activity/@ownedActivityNode.3/@storyPattern/@linkVariable.4" bindingOperator="DESTROY" bindingState="BOUND"/>
            <linkVariable name="markers" target="//Container/count/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.1" source="//Container/count/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.0" type="//Container/markers"/>
            <linkVariable name="markers" target="//Container/count/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.2" source="//Container/count/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.0" type="//Container/markers"/>
            <linkVariable name="markers" target="//Container/count/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.3" source="//Container/count/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.0" type="//Container/markers"/>
            <linkVariable name="counters" target="//Container/count/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.4" source="//Container/count/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.0" type="//Container/counters" bindingOperator="CREATE"/>
            <linkVariable name="counters" target="//Container/count/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.5" source="//Container/count/@activity/@ownedActivityNode.3/@storyPattern/@objectVariable.0" type="//Container/counters" bindingOperator="DESTROY"/>
          </storyPattern>
        </ownedActivityNode>
        <ownedActivityNode xsi:type="activities:StopNode" incoming="//Container/count/@activity/@ownedActivityEdge.3 //Container/count/@activity/@ownedActivityEdge.4 //Container/count/@activity/@ownedActivityEdge.5"/>
      </activity>
    </eOperations>
    <eOperations xsi:type="activities:MoflonEOperation" name="empty"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="counters" eType="//Counter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="markers" upperBound="-1" eType="//Marker" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Marker">
    <eOperations xsi:type="activities:MoflonEOperation" name="nothing"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Counter"/>
  <eClassifiers xsi:type="ecore:EClass" name="One" eSuperTypes="//Counter"/>
  <eClassifiers xsi:type="ecore:EClass" name="Two" eSuperTypes="//Counter"/>
  <eClassifiers xsi:type="ecore:EClass" name="Three" eSuperTypes="//Counter"/>
</ecore:EPackage>
